version: '3.7'
services:
  pgreplica1:
    image: postgres:latest
    container_name: pgreplica1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=social_network
    volumes:
      - ./replica1-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - pgmaster
    networks:
      - general
  
  pgreplica2:
    image: postgres:latest
    container_name: pgreplica2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=social_network
    volumes:
      - ./replica2-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      - pgmaster
    networks:
      - general
