version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    volumes:
      - ./data:/var/lib/postgresql/data
      - ../social_network/migrations/202403231940_users.sql:/docker-entrypoint-initdb.d/202403231940_users.sql
      - ../common/migrations/202403241129_test_table.sql:/docker-entrypoint-initdb.d/202403241129_test_table.sql
    ports:
      - 5432:5432